import { useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { forgotPassword, resetPassword } from './authApi'
import { useAuth } from './AuthProvider'

function AuthCard({ title, children }: { title: string; children: React.ReactNode }) { return <main className="grid min-h-screen place-items-center bg-background p-4"><section className="w-full max-w-md rounded-2xl border border-border bg-surface p-6 shadow-sm sm:p-8"><Link to="/" className="text-lg font-bold text-primary">LAK</Link><h1 className="mt-6 text-2xl font-bold text-text-primary">{title}</h1>{children}</section></main> }
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { const id = props.name; return <label className="block text-sm font-medium text-text-primary" htmlFor={id}>{label}<input id={id} {...props} className="mt-1 min-h-11 w-full rounded-lg border border-border px-3 text-text-primary outline-none focus:border-info focus:ring-2 focus:ring-info/20" /></label> }
function ErrorMessage({ value }: { value: string | null }) { return value ? <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-error">{value}</p> : null }
function Submit({ children, pending }: { children: string; pending: boolean }) { return <button type="submit" disabled={pending} className="min-h-11 w-full rounded-lg bg-primary px-4 py-2 font-semibold text-white transition-colors hover:bg-primary-hover disabled:opacity-60">{pending ? 'Đang xử lý…' : children}</button> }

export function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); setError(null); try { await login(String(form.get('email')), String(form.get('password'))); navigate((location.state as { from?: string } | null)?.from ?? '/', { replace: true }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Không thể đăng nhập.') } finally { setPending(false) } }
  return <AuthCard title="Đăng nhập"><form className="mt-6 space-y-4" onSubmit={submit}><ErrorMessage value={error}/><Field label="Email" name="email" type="email" autoComplete="email" required/><Field label="Mật khẩu" name="password" type="password" autoComplete="current-password" required/><Submit pending={pending}>Đăng nhập</Submit></form><div className="mt-5 flex justify-between text-sm"><Link className="text-primary underline" to="/forgot-password">Quên mật khẩu?</Link><Link className="text-primary underline" to="/register">Đăng ký</Link></div></AuthCard>
}

export function RegisterPage() {
  const { register } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get('password')); if (password !== String(form.get('confirmPassword'))) { setError('Xác nhận mật khẩu không khớp.'); return } setPending(true); setError(null); try { await register(String(form.get('fullName')), String(form.get('email')), password); navigate('/', { replace: true }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Không thể đăng ký.') } finally { setPending(false) } }
  return <AuthCard title="Đăng ký tài khoản"><form className="mt-6 space-y-4" onSubmit={submit}><ErrorMessage value={error}/><Field label="Họ tên" name="fullName" autoComplete="name" required/><Field label="Email" name="email" type="email" autoComplete="email" required/><Field label="Mật khẩu (ít nhất 12 ký tự)" name="password" type="password" autoComplete="new-password" minLength={12} required/><Field label="Xác nhận mật khẩu" name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required/><Submit pending={pending}>Đăng ký</Submit></form><p className="mt-5 text-sm text-text-secondary">Đã có tài khoản? <Link className="text-primary underline" to="/login">Đăng nhập</Link></p></AuthCard>
}

export function ForgotPasswordPage() { const [email, setEmail] = useState(''); const [done, setDone] = useState(false); const [error, setError] = useState<string | null>(null); async function submit(e: FormEvent) { e.preventDefault(); setError(null); try { await forgotPassword(email); setDone(true) } catch { setError('Không thể gửi yêu cầu. Vui lòng thử lại.') } } return <AuthCard title="Quên mật khẩu"><p className="mt-2 text-sm text-text-secondary">Nếu tài khoản tồn tại, hệ thống sẽ gửi hướng dẫn tới email của bạn.</p>{done ? <p className="mt-6 rounded-lg bg-green-50 p-3 text-sm text-success">Yêu cầu đã được tiếp nhận.</p> : <form className="mt-6 space-y-4" onSubmit={submit}><ErrorMessage value={error}/><Field label="Email" name="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required/><Submit pending={false}>Gửi hướng dẫn</Submit></form>}</AuthCard> }

export function ResetPasswordPage() { const [params] = useSearchParams(); const navigate = useNavigate(); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState(false); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const password = String(new FormData(e.currentTarget).get('password')); const token = params.get('token'); if (!token) { setError('Liên kết đặt lại mật khẩu không hợp lệ.'); return } try { await resetPassword(token, password); setDone(true); window.setTimeout(() => navigate('/login'), 1200) } catch { setError('Liên kết đặt lại mật khẩu không hợp lệ hoặc đã hết hạn.') } } return <AuthCard title="Đặt lại mật khẩu">{done ? <p className="mt-6 text-sm text-success">Đã cập nhật mật khẩu. Đang chuyển tới trang đăng nhập…</p> : <form className="mt-6 space-y-4" onSubmit={submit}><ErrorMessage value={error}/><Field label="Mật khẩu mới (ít nhất 12 ký tự)" name="password" type="password" minLength={12} required/><Submit pending={false}>Cập nhật mật khẩu</Submit></form>}</AuthCard> }
