import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

export const LANGUAGE_KEY = 'lak-language'
export type LanguageCode = 'vi' | 'en'

const translations = {
  vi: {
    translation: {
      appTitle: 'LAK Cinema | Đặt vé xem phim', language: 'Ngôn ngữ', movies: 'Phim', cinemas: 'Rạp', search: 'Tìm phim, rạp...', searchLabel: 'Tìm phim hoặc rạp', myTickets: 'Vé của tôi', account: 'Tài khoản', profile: 'Hồ sơ', billing: 'Thông tin hóa đơn', signIn: 'Đăng nhập', signOut: 'Đăng xuất', home: 'Trang chủ', allRights: 'Tất cả quyền được bảo lưu.', tagline: 'Điện ảnh kết nối cảm xúc, đặt vé an toàn và rõ ràng.',
      featured: 'Phim nổi bật tuần này', bookNow: 'Đặt vé ngay', nowShowing: 'Phim đang chiếu', comingSoon: 'Phim sắp chiếu', lakCinemas: 'Rạp LAK', all: 'Xem tất cả', minutes: '{{count}} phút', genresPending: 'Đang cập nhật thể loại', loadError: 'Không thể tải dữ liệu.', retry: 'Thử lại', noNowShowing: 'Chưa có phim đang chiếu.', noComingSoon: 'Chưa có phim sắp chiếu.', noCinemas: 'Chưa có chi nhánh đang hoạt động.',
      searchMovie: 'Tìm theo tên phim', genre: 'Thể loại', allGenres: 'Tất cả thể loại', apply: 'Áp dụng', noMovies: 'Không tìm thấy phim phù hợp', clearFilters: 'Xóa bộ lọc', allMovies: 'Tất cả phim', releaseDate: 'Khởi chiếu {{date}}', country: 'Quốc gia', director: 'Đạo diễn', cast: 'Diễn viên', synopsis: 'Nội dung phim', synopsisPending: 'Thông tin phim đang được cập nhật.', chooseShowtime: 'Chọn suất chiếu', trailer: 'Xem trailer', chooseCinemaHint: 'Chọn chi nhánh thuận tiện để xem lịch chiếu.',
      explore: 'Khám phá', offers: 'Ưu đãi', support: 'Hỗ trợ', faq: 'Câu hỏi thường gặp', terms: 'Điều khoản sử dụng', privacy: 'Chính sách bảo mật', contact: 'Liên hệ', connect: 'Kết nối với chúng tôi', downloadApp: 'Tải ứng dụng LAK', comingUpdate: 'sắp cập nhật',
      quickBooking: 'Đặt vé nhanh', quickBookingHint: 'Chỉ hiển thị rạp, ngày và suất chiếu đang mở bán.', chooseMovie: 'Chọn phim', chooseCinema: 'Chọn rạp', chooseDate: 'Chọn ngày', chooseSession: 'Chọn suất chiếu', loadingCinemas: 'Đang tải rạp…', loadingSessions: 'Đang tải suất…', quickBuy: 'Mua vé nhanh', moviesError: 'Không thể tải danh sách phim.', availabilityError: 'Không thể tải rạp và ngày chiếu.', noOpenSessions: 'Phim này chưa có suất chiếu đang mở bán.', showtimesError: 'Không thể tải suất chiếu.', noSessionsDate: 'Không còn suất chiếu mở bán trong ngày đã chọn.',
      authWelcome: 'Chào mừng bạn trở lại! Đăng nhập để tiếp tục đặt vé và khám phá những bộ phim hấp dẫn tại LAK.', email: 'Email', password: 'Mật khẩu', enterEmail: 'Nhập email của bạn', enterPassword: 'Nhập mật khẩu', showPassword: 'Hiện mật khẩu', hidePassword: 'Ẩn mật khẩu', processing: 'Đang xử lý…', or: 'Hoặc', noAccount: 'Chưa có tài khoản?', register: 'Đăng ký', registerTitle: 'Đăng ký tài khoản', agreePrefix: 'Bằng việc đăng nhập, bạn đồng ý với', and: 'và', lakPrivacy: 'Chính sách bảo mật của LAK Cinema', haveAccount: 'Đã có tài khoản?', fullName: 'Họ tên', passwordMin: 'Mật khẩu (ít nhất 12 ký tự)', confirmPassword: 'Xác nhận mật khẩu', passwordMismatch: 'Xác nhận mật khẩu không khớp.', forgotPassword: 'Quên mật khẩu', forgotHint: 'Nếu tài khoản tồn tại, hệ thống sẽ gửi hướng dẫn tới email của bạn.', requestAccepted: 'Yêu cầu đã được tiếp nhận.', sendInstructions: 'Gửi hướng dẫn', resetPassword: 'Đặt lại mật khẩu', invalidResetLink: 'Liên kết đặt lại mật khẩu không hợp lệ.', expiredResetLink: 'Liên kết đặt lại mật khẩu không hợp lệ hoặc đã hết hạn.', passwordUpdated: 'Đã cập nhật mật khẩu. Đang chuyển tới trang đăng nhập…', newPassword: 'Mật khẩu mới (ít nhất 12 ký tự)', updatePassword: 'Cập nhật mật khẩu', signInError: 'Không thể đăng nhập.', registerError: 'Không thể đăng ký.', requestError: 'Không thể gửi yêu cầu. Vui lòng thử lại.',
      accountTitle: 'Tài khoản LAK', greeting: 'Xin chào, {{name}}', you: 'bạn', dashboardHint: 'Theo dõi vé và trạng thái giao dịch của bạn tại một nơi.', upcomingTicket: 'Vé sắp xem', seats: 'Ghế', viewTicket: 'Xem vé', noUpcomingTicket: 'Bạn chưa có vé sắp xem.', exploreMovies: 'Khám phá phim', quickActions: 'Thao tác nhanh', accountActions: 'Thao tác tài khoản', bookingHistory: 'Lịch sử đặt vé', newBooking: 'Đặt vé mới', recentBookings: 'Đặt vé gần đây', recentHint: 'Các booking mới nhất của bạn.', viewHistory: 'Xem lịch sử', noBookings: 'Bạn chưa có booking nào.', bookedOn: 'Đặt lúc {{date}}', viewBooking: 'Xem booking', accountLoadError: 'Không thể tải dữ liệu tài khoản. Vui lòng thử lại.',
      statusShowtimeCancelled: 'Suất chiếu đã hủy', statusRefundFailed: 'Hoàn tiền cần hỗ trợ', statusRefunded: 'Đã hoàn tiền', statusRefundPending: 'Đang hoàn tiền', statusPaid: 'Đã thanh toán', statusPaymentReview: 'Đang đối soát thanh toán', statusPendingPayment: 'Chờ thanh toán', statusPaymentUpdating: 'Đang cập nhật thanh toán', statusExpired: 'Đã hết hạn', statusCancelled: 'Đã hủy', statusUpdating: 'Đang cập nhật trạng thái', noticeIssue: 'Có vấn đề', noticeAction: 'Cần bạn xử lý', noticeProcessing: 'Đang được xử lý', noticeRefundTrack: 'Vui lòng theo dõi trạng thái hoàn tiền.', noticeNoPayment: 'Bạn không cần tiếp tục thanh toán.', noticeStatus: 'Trạng thái: {{status}}.', noticeShowtimeCancelled: 'Suất chiếu của booking {{code}} đã bị hủy; vé không còn hiệu lực. {{detail}}', noticeRefundFailed: 'Bộ phận hỗ trợ đang xử lý hoàn tiền cho booking {{code}}. Bạn không cần gửi yêu cầu mới.', noticeCompletePayment: 'Hoàn tất thanh toán', noticeCompletePaymentHint: 'Booking {{code}} còn trong hạn thanh toán. Trang xác nhận sẽ kiểm tra lại thời hạn trước khi tiếp tục.', noticeContinuePayment: 'Tiếp tục thanh toán', noticeVerifyPayment: 'Đang xác minh thanh toán', noticeVerifyPaymentHint: 'Booking {{code}} đang được hệ thống xác minh. Vui lòng không thanh toán lại.', noticeRefundProcessing: 'Đang xử lý hoàn tiền', noticeRefundProcessingHint: 'Yêu cầu hoàn tiền cho booking {{code}} đã được tiếp nhận.', track: 'Theo dõi',
      adminCinemas: 'Rạp & phòng', adminShowtimes: 'Suất chiếu', adminPricing: 'Bảng giá', adminBookings: 'Booking', adminPayments: 'Thanh toán', adminRefunds: 'Hoàn tiền', adminUsers: 'Người dùng', adminReports: 'Báo cáo', adminSeatMap: 'Sơ đồ ghế', adminTitle: 'Quản trị LAK', adminNavigation: 'Điều hướng quản trị', adminUnavailable: 'Màn hình chưa có API quản trị', adminAccount: 'Tài khoản quản trị', adminRole: 'Quản trị viên', adminViewWebsite: 'Xem website', adminScopedData: 'Dữ liệu theo phân quyền', adminMenu: 'Menu quản trị', adminOpenMenu: 'Mở menu quản trị', adminCloseMenu: 'Đóng menu quản trị', staffArea: 'Khu vực nhân viên', signedInRole: 'Đăng nhập với vai trò: {{roles}}', forbidden: 'Bạn không có quyền truy cập', back: 'Quay lại',
    },
  },
  en: {
    translation: {
      appTitle: 'LAK Cinema | Book movie tickets', language: 'Language', movies: 'Movies', cinemas: 'Cinemas', search: 'Search movies, cinemas...', searchLabel: 'Search movies or cinemas', myTickets: 'My tickets', account: 'Account', profile: 'Profile', billing: 'Billing information', signIn: 'Sign in', signOut: 'Sign out', home: 'Home', allRights: 'All rights reserved.', tagline: 'Cinema connects us. Book tickets safely and clearly.',
      featured: 'Featured this week', bookNow: 'Book now', nowShowing: 'Now showing', comingSoon: 'Coming soon', lakCinemas: 'LAK cinemas', all: 'View all', minutes: '{{count}} min', genresPending: 'Genres coming soon', loadError: 'Unable to load data.', retry: 'Try again', noNowShowing: 'No movies showing now.', noComingSoon: 'No upcoming movies.', noCinemas: 'No active cinemas yet.',
      searchMovie: 'Search by movie title', genre: 'Genre', allGenres: 'All genres', apply: 'Apply', noMovies: 'No matching movies found', clearFilters: 'Clear filters', allMovies: 'All movies', releaseDate: 'Release date {{date}}', country: 'Country', director: 'Director', cast: 'Cast', synopsis: 'Synopsis', synopsisPending: 'Movie information is being updated.', chooseShowtime: 'Choose a showtime', trailer: 'Watch trailer', chooseCinemaHint: 'Choose a convenient cinema to view showtimes.',
      explore: 'Explore', offers: 'Offers', support: 'Support', faq: 'FAQ', terms: 'Terms of use', privacy: 'Privacy policy', contact: 'Contact', connect: 'Connect with us', downloadApp: 'Get the LAK app', comingUpdate: 'coming soon',
      quickBooking: 'Quick booking', quickBookingHint: 'Only cinemas, dates and showtimes currently on sale are shown.', chooseMovie: 'Choose a movie', chooseCinema: 'Choose a cinema', chooseDate: 'Choose a date', chooseSession: 'Choose a showtime', loadingCinemas: 'Loading cinemas…', loadingSessions: 'Loading showtimes…', quickBuy: 'Book quickly', moviesError: 'Unable to load movies.', availabilityError: 'Unable to load cinemas and dates.', noOpenSessions: 'No showtimes are on sale for this movie.', showtimesError: 'Unable to load showtimes.', noSessionsDate: 'No showtimes are on sale for the selected date.',
      authWelcome: 'Welcome back! Sign in to book tickets and explore movies at LAK.', email: 'Email', password: 'Password', enterEmail: 'Enter your email', enterPassword: 'Enter your password', showPassword: 'Show password', hidePassword: 'Hide password', processing: 'Processing…', or: 'Or', noAccount: "Don't have an account?", register: 'Register', registerTitle: 'Create an account', agreePrefix: 'By signing in, you agree to the', and: 'and', lakPrivacy: 'LAK Cinema Privacy Policy', haveAccount: 'Already have an account?', fullName: 'Full name', passwordMin: 'Password (at least 12 characters)', confirmPassword: 'Confirm password', passwordMismatch: 'Passwords do not match.', forgotPassword: 'Forgot password', forgotHint: 'If your account exists, we will email you instructions.', requestAccepted: 'Your request has been received.', sendInstructions: 'Send instructions', resetPassword: 'Reset password', invalidResetLink: 'Invalid password reset link.', expiredResetLink: 'The password reset link is invalid or expired.', passwordUpdated: 'Password updated. Redirecting to sign in…', newPassword: 'New password (at least 12 characters)', updatePassword: 'Update password', signInError: 'Unable to sign in.', registerError: 'Unable to register.', requestError: 'Unable to send your request. Please try again.',
      accountTitle: 'LAK account', greeting: 'Hello, {{name}}', you: 'you', dashboardHint: 'Track your tickets and transactions in one place.', upcomingTicket: 'Upcoming ticket', seats: 'Seats', viewTicket: 'View ticket', noUpcomingTicket: 'You have no upcoming tickets.', exploreMovies: 'Explore movies', quickActions: 'Quick actions', accountActions: 'Account actions', bookingHistory: 'Booking history', newBooking: 'Book tickets', recentBookings: 'Recent bookings', recentHint: 'Your latest bookings.', viewHistory: 'View history', noBookings: 'You have no bookings yet.', bookedOn: 'Booked on {{date}}', viewBooking: 'View booking', accountLoadError: 'Unable to load account data. Please try again.',
      statusShowtimeCancelled: 'Showtime cancelled', statusRefundFailed: 'Refund needs support', statusRefunded: 'Refunded', statusRefundPending: 'Refund in progress', statusPaid: 'Paid', statusPaymentReview: 'Payment under review', statusPendingPayment: 'Awaiting payment', statusPaymentUpdating: 'Payment status updating', statusExpired: 'Expired', statusCancelled: 'Cancelled', statusUpdating: 'Status updating', noticeIssue: 'Needs attention', noticeAction: 'Action needed', noticeProcessing: 'In progress', noticeRefundTrack: 'Please track the refund status.', noticeNoPayment: 'You do not need to continue payment.', noticeStatus: 'Status: {{status}}.', noticeShowtimeCancelled: 'The showtime for booking {{code}} was cancelled; the ticket is no longer valid. {{detail}}', noticeRefundFailed: 'Support is processing the refund for booking {{code}}. You do not need to submit another request.', noticeCompletePayment: 'Complete payment', noticeCompletePaymentHint: 'Booking {{code}} is still within the payment period. The checkout page will check the deadline again.', noticeContinuePayment: 'Continue payment', noticeVerifyPayment: 'Verifying payment', noticeVerifyPaymentHint: 'Booking {{code}} is being verified. Please do not pay again.', noticeRefundProcessing: 'Processing refund', noticeRefundProcessingHint: 'The refund request for booking {{code}} has been received.', track: 'Track',
      adminCinemas: 'Cinemas & rooms', adminShowtimes: 'Showtimes', adminPricing: 'Pricing', adminBookings: 'Bookings', adminPayments: 'Payments', adminRefunds: 'Refunds', adminUsers: 'Users', adminReports: 'Reports', adminSeatMap: 'Seat map', adminTitle: 'LAK administration', adminNavigation: 'Admin navigation', adminUnavailable: 'This screen has no admin API yet', adminAccount: 'Admin account', adminRole: 'Administrator', adminViewWebsite: 'View website', adminScopedData: 'Data limited by access scope', adminMenu: 'Admin menu', adminOpenMenu: 'Open admin menu', adminCloseMenu: 'Close admin menu', staffArea: 'Staff area', signedInRole: 'Signed in with roles: {{roles}}', forbidden: 'You do not have access', back: 'Go back',
    },
  },
} as const

function initialLanguage(): LanguageCode {
  try { return window.localStorage.getItem(LANGUAGE_KEY) === 'en' ? 'en' : 'vi' } catch { return 'vi' }
}

void i18n.use(initReactI18next).init({ resources: translations, lng: initialLanguage(), fallbackLng: 'vi', supportedLngs: ['vi', 'en'], interpolation: { escapeValue: false } })

const extraTranslations = {
  vi: { adminManagement: 'Quản lý', apiGenericError: 'Không thể hoàn tất yêu cầu. Vui lòng thử lại.', apiConnectionError: 'Không thể kết nối tới hệ thống. Vui lòng thử lại.', apiInvalidCredentials: 'Email hoặc mật khẩu không đúng.', apiAccountLocked: 'Tài khoản đang bị khóa.', apiEmailRegistered: 'Email đã được đăng ký.', apiPasswordResetInvalid: 'Liên kết đặt lại mật khẩu không hợp lệ hoặc đã hết hạn.', apiValidationFailed: 'Thông tin nhập không hợp lệ.', apiBookingNotFound: 'Không tìm thấy booking.', apiBookingForbidden: 'Bạn không có quyền xem booking này.', apiSeatHoldInactive: 'Thời gian giữ ghế đã hết. Vui lòng chọn lại ghế.', apiPaymentReview: 'Giao dịch đang được xác minh. Vui lòng không thanh toán lại.' },
  en: { adminManagement: 'Management', apiGenericError: 'Unable to complete the request. Please try again.', apiConnectionError: 'Unable to connect. Please try again.', apiInvalidCredentials: 'Incorrect email or password.', apiAccountLocked: 'This account is locked.', apiEmailRegistered: 'This email is already registered.', apiPasswordResetInvalid: 'The password reset link is invalid or expired.', apiValidationFailed: 'The submitted information is invalid.', apiBookingNotFound: 'Booking not found.', apiBookingForbidden: 'You cannot view this booking.', apiSeatHoldInactive: 'Your seat hold has expired. Please select seats again.', apiPaymentReview: 'The transaction is being verified. Please do not pay again.' },
} as const
for (const language of ['vi', 'en'] as const) i18n.addResourceBundle(language, 'translation', extraTranslations[language], true, true)

i18n.on('languageChanged', (language) => {
  document.documentElement.lang = language === 'en' ? 'en' : 'vi'
  document.title = i18n.t('appTitle')
  try { window.localStorage.setItem(LANGUAGE_KEY, document.documentElement.lang) } catch { /* Storage can be unavailable. */ }
})
document.documentElement.lang = i18n.language === 'en' ? 'en' : 'vi'
document.title = i18n.t('appTitle')

export function displayLocale(language: string): string { return language === 'en' ? 'en-US' : 'vi-VN' }
export default i18n
