spring:
  config:
    activate:
      on-profile: prod

server:
  forward-headers-strategy: framework

logging:
  level:
    root: ${LOG_LEVEL:INFO}

app:
  auth:
    cookie-secure: ${AUTH_COOKIE_SECURE:true}
